CREATE DATABASE cptool ENCODING=UTF8;
GRANT ALL ON ALL TABLES IN SCHEMA public TO cpt_admin WITH GRANT OPTION;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO cpt_admin WITH GRANT OPTION;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO cpt_admin WITH GRANT OPTION;
